---
apiVersion: v1
kind: Service
metadata:
  name: es-exporter
  labels:
    name: es-exporter
  namespace: devops
spec:
  ports:
    - name: exporter
      port: 9114
      targetPort: 9114
  selector:
    app: "es-exporter"
