#Elastic Search Config File
cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER:false}
  data: ${NODE_DATA:false}
  name: ${NODE_NAME}
  ingest: ${NODE_INGEST:false}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES:10}

network.host: ${NETWORK_HOST:_site_}

path:
  data: /var/lib/es
  logs: /var/log/es

bootstrap:
  memory_lock: false

http:
  enabled: ${HTTP_ENABLE:true}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE:false}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN:*}

discovery:
  zen:
    ping.unicast.hosts: es-discovery
    minimum_master_nodes: ${NUMBER_OF_MASTERS:1}
#
#xpack.monitoring.exporters.my_local:
#  type: local
#  use_ingest: false

xpack:
  security:
    enabled: false
#        authc:
#          realms:
#            ldap1:
#              type: ldap
#              order: 0
#              url: "ldap://10.6.10.25:389"
#              bind_dn: "admin,OU=Service Accounts,OU=devlabs,DC=devlabs,DC=corp"
#              bind_password: dev_password
#              user_search:
#                base_dn: "dc=example,dc=com"
#                attribute: userPrincipalName
#              group_search:
#                base_dn: "DC=devlabs,DC=corp"
#              files:
#                role_mapping: "/usr/share/es/config/role_mapping.yml"
#              unmapped_groups_as_roles: false